# Generated by Django 4.2 on 2023-06-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwanderer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
    ]
