# Generated by Django 4.2 on 2023-06-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnwanderer', '0004_detailedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detailedPost',
        ),
    ]
