# Generated by Django 4.2 on 2023-06-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwanderer', '0006_remove_blogpost_updated_at_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
