# Generated by Django 4.2 on 2023-06-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwanderer', '0007_blogpost_full_description_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='blog_galleries/%Y/%m/%d/'),
        ),
    ]
