# Generated by Django 4.2 on 2023-06-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnwanderer', '0009_rename_content_blogpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pnwanderer.blogpost'),
        ),
    ]
