# Generated by Django 4.2 on 2023-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnwanderer', '0010_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(upload_to='blog_galleries/%Y/%m/%d/'),
        ),
    ]
