# Generated by Django 4.2 on 2023-07-04 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pnwanderer', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
